title: Trevor Malard
description: Trevor Malard, Tokyo-based digital creative. Web design and Video production.

links:
  - video
  - web
  - contact

social:
  email: trevormalard@gmail.com
  vimeo: https://vimeo.com/rsdz
  github: https://github.com/fire-pls
  instagram: https://instagram.com/_rsdz
