title: Trevor Malard
description: Trevor Malard, Tokyo-based digital creative. Web design and Video production.

links:
  - video
  - web
  - contact

social:
  email: contact@tmalard.com
  vimeo: https://vimeo.com/tmalard
  github: https://github.com/fire-pls
