title: Trevor Malard
description: Portfolio for digital creative Trevor Malard.

links:
  - web
  - video
  - contact

social:
  vimeo: https://vimeo.com/rsdz
  github: https://github.com/fire-pls
  linkedin: https://linkedin.com/in/trevor-malard
  instagram: https://instagram.com/_rsdz
