title: Trevor Malard
description: Trevor Malard, Tokyo-based digital creative. Web design and Video production.

links:
  - video
  - web
  - contact

social:
  vimeo: https://vimeo.com/rsdz
  github: https://github.com/fire-pls
  linkedin: https://linkedin.com/in/trevor-malard
  instagram: https://instagram.com/_rsdz
